### ISSUE TITLE
add 12rambau as a maintainer

### ISSUE THREAD

**Issue by 12rambau** [conda-forge/rio-vrt-feedstock#2]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

@conda-forge/python 

I don't know who created this conda feedstock but I don't remember being tagged when it was created even though I'm the owner of the wired repository and the pypi project. 
Can I be added as a maintainer to this one so I keep both conda and pypi deployment in sync (we were unable to update osmnx yesterday because I cannot validate the PR for 0.3.1) 

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by ocefpaf** [comment]
> @conda-forge/python

This is the team that handles the Python package feedstock.

If you wish to be part of this feedstock you need to contact the maintainer first and, if they are unresponsive for at least 1 week, you should contact the core team.

**Comment by 12rambau** [comment]
thanks @ocefpaf, @savente93 could you add me as a maintainer using the conda-forge bot ?

**Comment by aslowwriter** [comment]
@12rambau If you're interested I'm very happy to hand the repository over to you
